/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: channel_matrx.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "channel_matrx.pb-c.h"
void   nrmatrix__ue__srs__pack__init
                     (NRMatrix__UESRSPACK         *message)
{
  static const NRMatrix__UESRSPACK init_value = NRMATRIX__UE__SRS__PACK__INIT;
  *message = init_value;
}
size_t nrmatrix__ue__srs__pack__get_packed_size
                     (const NRMatrix__UESRSPACK *message)
{
  assert(message->base.descriptor == &nrmatrix__ue__srs__pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nrmatrix__ue__srs__pack__pack
                     (const NRMatrix__UESRSPACK *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nrmatrix__ue__srs__pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nrmatrix__ue__srs__pack__pack_to_buffer
                     (const NRMatrix__UESRSPACK *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nrmatrix__ue__srs__pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NRMatrix__UESRSPACK *
       nrmatrix__ue__srs__pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NRMatrix__UESRSPACK *)
     protobuf_c_message_unpack (&nrmatrix__ue__srs__pack__descriptor,
                                allocator, len, data);
}
void   nrmatrix__ue__srs__pack__free_unpacked
                     (NRMatrix__UESRSPACK *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nrmatrix__ue__srs__pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nrmatrix__nr__srs__pack__init
                     (NRMatrix__NRSRSPACK         *message)
{
  static const NRMatrix__NRSRSPACK init_value = NRMATRIX__NR__SRS__PACK__INIT;
  *message = init_value;
}
size_t nrmatrix__nr__srs__pack__get_packed_size
                     (const NRMatrix__NRSRSPACK *message)
{
  assert(message->base.descriptor == &nrmatrix__nr__srs__pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nrmatrix__nr__srs__pack__pack
                     (const NRMatrix__NRSRSPACK *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nrmatrix__nr__srs__pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nrmatrix__nr__srs__pack__pack_to_buffer
                     (const NRMatrix__NRSRSPACK *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nrmatrix__nr__srs__pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NRMatrix__NRSRSPACK *
       nrmatrix__nr__srs__pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NRMatrix__NRSRSPACK *)
     protobuf_c_message_unpack (&nrmatrix__nr__srs__pack__descriptor,
                                allocator, len, data);
}
void   nrmatrix__nr__srs__pack__free_unpacked
                     (NRMatrix__NRSRSPACK *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nrmatrix__nr__srs__pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nrmatrix__nr__srs__info__init
                     (NRMatrix__NRSRSINFO         *message)
{
  static const NRMatrix__NRSRSINFO init_value = NRMATRIX__NR__SRS__INFO__INIT;
  *message = init_value;
}
size_t nrmatrix__nr__srs__info__get_packed_size
                     (const NRMatrix__NRSRSINFO *message)
{
  assert(message->base.descriptor == &nrmatrix__nr__srs__info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nrmatrix__nr__srs__info__pack
                     (const NRMatrix__NRSRSINFO *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nrmatrix__nr__srs__info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nrmatrix__nr__srs__info__pack_to_buffer
                     (const NRMatrix__NRSRSINFO *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nrmatrix__nr__srs__info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NRMatrix__NRSRSINFO *
       nrmatrix__nr__srs__info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NRMatrix__NRSRSINFO *)
     protobuf_c_message_unpack (&nrmatrix__nr__srs__info__descriptor,
                                allocator, len, data);
}
void   nrmatrix__nr__srs__info__free_unpacked
                     (NRMatrix__NRSRSINFO *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nrmatrix__nr__srs__info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nrmatrix__result__init
                     (NRMatrix__RESULT         *message)
{
  static const NRMatrix__RESULT init_value = NRMATRIX__RESULT__INIT;
  *message = init_value;
}
size_t nrmatrix__result__get_packed_size
                     (const NRMatrix__RESULT *message)
{
  assert(message->base.descriptor == &nrmatrix__result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nrmatrix__result__pack
                     (const NRMatrix__RESULT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nrmatrix__result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nrmatrix__result__pack_to_buffer
                     (const NRMatrix__RESULT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nrmatrix__result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NRMatrix__RESULT *
       nrmatrix__result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NRMatrix__RESULT *)
     protobuf_c_message_unpack (&nrmatrix__result__descriptor,
                                allocator, len, data);
}
void   nrmatrix__result__free_unpacked
                     (NRMatrix__RESULT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nrmatrix__result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nrmatrix__ue__srs__pack__field_descriptors[1] =
{
  {
    "ue_info",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NRMatrix__UESRSPACK, n_ue_info),
    offsetof(NRMatrix__UESRSPACK, ue_info),
    &nrmatrix__nr__srs__pack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nrmatrix__ue__srs__pack__field_indices_by_name[] = {
  0,   /* field[0] = ue_info */
};
static const ProtobufCIntRange nrmatrix__ue__srs__pack__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nrmatrix__ue__srs__pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NRMatrix.UE_SRS_PACK",
  "UESRSPACK",
  "NRMatrix__UESRSPACK",
  "NRMatrix",
  sizeof(NRMatrix__UESRSPACK),
  1,
  nrmatrix__ue__srs__pack__field_descriptors,
  nrmatrix__ue__srs__pack__field_indices_by_name,
  1,  nrmatrix__ue__srs__pack__number_ranges,
  (ProtobufCMessageInit) nrmatrix__ue__srs__pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nrmatrix__nr__srs__pack__field_descriptors[2] =
{
  {
    "matrix",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NRMatrix__NRSRSPACK, n_matrix),
    offsetof(NRMatrix__NRSRSPACK, matrix),
    &nrmatrix__nr__srs__info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRMatrix__NRSRSPACK, ue_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nrmatrix__nr__srs__pack__field_indices_by_name[] = {
  0,   /* field[0] = matrix */
  1,   /* field[1] = ue_id */
};
static const ProtobufCIntRange nrmatrix__nr__srs__pack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nrmatrix__nr__srs__pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NRMatrix.NR_SRS_PACK",
  "NRSRSPACK",
  "NRMatrix__NRSRSPACK",
  "NRMatrix",
  sizeof(NRMatrix__NRSRSPACK),
  2,
  nrmatrix__nr__srs__pack__field_descriptors,
  nrmatrix__nr__srs__pack__field_indices_by_name,
  1,  nrmatrix__nr__srs__pack__number_ranges,
  (ProtobufCMessageInit) nrmatrix__nr__srs__pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nrmatrix__nr__srs__info__field_descriptors[1] =
{
  {
    "prb_item",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NRMatrix__NRSRSINFO, n_prb_item),
    offsetof(NRMatrix__NRSRSINFO, prb_item),
    &nrmatrix__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nrmatrix__nr__srs__info__field_indices_by_name[] = {
  0,   /* field[0] = prb_item */
};
static const ProtobufCIntRange nrmatrix__nr__srs__info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nrmatrix__nr__srs__info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NRMatrix.NR_SRS_INFO",
  "NRSRSINFO",
  "NRMatrix__NRSRSINFO",
  "NRMatrix",
  sizeof(NRMatrix__NRSRSINFO),
  1,
  nrmatrix__nr__srs__info__field_descriptors,
  nrmatrix__nr__srs__info__field_indices_by_name,
  1,  nrmatrix__nr__srs__info__number_ranges,
  (ProtobufCMessageInit) nrmatrix__nr__srs__info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nrmatrix__result__field_descriptors[2] =
{
  {
    "image",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRMatrix__RESULT, image),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "real",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRMatrix__RESULT, real),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nrmatrix__result__field_indices_by_name[] = {
  0,   /* field[0] = image */
  1,   /* field[1] = real */
};
static const ProtobufCIntRange nrmatrix__result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nrmatrix__result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NRMatrix.RESULT",
  "RESULT",
  "NRMatrix__RESULT",
  "NRMatrix",
  sizeof(NRMatrix__RESULT),
  2,
  nrmatrix__result__field_descriptors,
  nrmatrix__result__field_indices_by_name,
  1,  nrmatrix__result__number_ranges,
  (ProtobufCMessageInit) nrmatrix__result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
